// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/payment/": {
            "post": {
                "description": "Make payment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Make payment",
                "parameters": [
                    {
                        "description": "Payment info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PaymentInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/handler.transactionInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.response"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/handler.response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.PaymentInfo": {
            "type": "object",
            "required": [
                "cardLastname",
                "cardName",
                "cardNumber",
                "cvv",
                "orderId",
                "paymentType",
                "totalPrice",
                "userId"
            ],
            "properties": {
                "cardDate": {
                    "type": "string"
                },
                "cardLastname": {
                    "type": "string"
                },
                "cardName": {
                    "type": "string"
                },
                "cardNumber": {
                    "type": "string"
                },
                "cvv": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "paymentType": {
                    "type": "string"
                },
                "totalPrice": {
                    "type": "number"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "domain.Transaction": {
            "type": "object",
            "properties": {
                "_": {
                    "type": "string"
                },
                "card_number": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "totalPrice": {
                    "type": "number"
                }
            }
        },
        "handler.response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.transactionInfo": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.Transaction"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "165.232.68.67:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Payment-Service API",
	Description:      "REST API for Payment",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
